
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'freetrade_test'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'freetrade_test'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for accounts, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"
on-run-start:
    - '{{create_udfs()}}'

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this accounts config, we tell dbt to build all models in the accounts/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  freetrade_test:
    # Config indicated by + and applies to all files under models/accounts/
    example:
      +materialized: view
