
version: 2

models:
  - name: account_cashflows
    description: "A superset of all cashflows going in/out of a customers account. These include buy/sell orders,
    deposits and withdrawals"
    columns:
      - name: customer_id
        description: "customer/client id"
        tests:
          - unique
          - not_null
      - name: log_datetime
        description: "datetime of cashflow log"
      - name: amount
        description: "amount in GBP of cashflow"
      - name: transaction_type
        description: "type of cashflow - e.g deposit, withdrawal, buy order, sell order"

  - name: withdrawable_cash_timeseries
    description: "withdrawable balance constructed from account cashflows"
    columns:
      - name: customer_id
        description: "customer/client id"
      - name: datetime
        description: "datetime of account balance snapshot - intervals of 6 hrs"
      - name: account_balance
        description: "withdrawable cash in account"

  - name: fx_revenue_cashflows
    description: "revenue events from US dollar buy/sell orders. Assumed 1% of order value"
    columns:
      - name: customer_id
        description: "customer/client id"
      - name: datetime
        description: "datetime of US buy/sell order settlement - and therefore revenue cashflow"
      - name: order_id
        description: "unique order id - fk to orders table"
      - name: amount
        description: "cash amount (GBP) of revenue cashflow (1% of order value)"

  - name: subscription_revenue_cashflows
    description: "revenue events from projected subscription payments"
    columns:
      - name: customer_id
        description: "customer/client id"
      - name: subscription_id
        description: "uniqiue subscription_id"
      - name: amount
        description: "amount of subscription payment (GBP)"
      - name: subscription_type
        description: "sipp or isa"
      - name: billing_date
        description: "date of billing - first one is 1 month after subscription start date"

  - name: revenue_cashflows
    description: "combined table of fx and subscription revenue cashflows"
    columns:
      - name: customer_id
        description: "customer/client id"
      - name: transaction_datetime
        description: "datetime of revenue cashflow"
      - name: amount
        description: "revenue amount (GBP)"
      - name: source
        description: "revenue source - isa, sipp or US FX"  





